# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  schedule:
    - cron: '* * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: python SteamMarketCandleStick.py
