# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule:
    - cron: '* * * * *'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pandas numpy requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: python SteamMarketCandleStick.py
    - name: check for changes
      run: git status
    - name: stage changed files
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
    - name: commit changed files
      run: git commit -m "Auto updating TODO.txt"
    - name: fetch from master
      run: git fetch origin main
    - name: push code to master
      run: git push origin HEAD:main
